version: 2
jobs:
  build:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run: yarn install
      - run: CI=true yarn build
  test:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run: yarn install
      - run: CI=true yarn test

workflows:
  version: 2
  test_my_app:
    jobs:
      - build
      - test
